export const dom = {
  dayGrid: document.querySelector("#dayGrid"),
  dayPanel: document.querySelector("#dayPanel"),
  panelContent: document.querySelector("#panelContent"),
  closePanel: document.querySelector("#closePanel"),
  orderForm: document.querySelector("#orderForm"),
  orderList: document.querySelector("#orderList"),
  orderSubmit: document.querySelector("#orderSubmit"),
  orderCancel: document.querySelector("#orderCancel"),
  tripSettingsForm: document.querySelector("#tripSettingsForm"),
  tripStartDate: document.querySelector("#tripStartDate"),
  tripDayCount: document.querySelector("#tripDayCount"),
  clearItinerary: document.querySelector("#clearItinerary"),
  wishlistForm: document.querySelector("#wishlistForm"),
  wishDay: document.querySelector("#wishDay"),
  wishBoard: document.querySelector("#wishBoard"),
  photoInput: document.querySelector("#photoInput"),
  photoGrid: document.querySelector("#photoGrid"),
  mapShell: document.querySelector("#mapShell"),
  syncStatus: document.querySelector("#syncStatus"),
  langToggle: document.querySelector("#langToggle"),
};
